name: "CI codecheck"

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Run Golangci lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: -E exportloopref,gofmt --timeout=30m
